### ISSUE TITLE
[tools] Add Windows support

### ISSUE THREAD

**Issue by linonetwo** [codefoundries/UniversalRelayBoilerplate#134]
λ react-native run-android
Android project not found. Maybe run react-native android first?

I tried npm run start and npm run dev, and running all the commands under root of project folder.

**Comment by thelordoftheboards** [comment]
It seems that some of the Android files were not updated during the latest RN upgrade.

**Comment by thelordoftheboards** [comment]
I added some of the files but the build is still failing:

```
$ react-native android
 conflict .gitignore
? Overwrite .gitignore? do not overwrite
     skip .gitignore
identical .watchmanconfig
identical .buckconfig
identical index.android.js
identical android/app/BUCK
identical android/app/build.gradle
identical android/app/proguard-rules.pro
   create android/app/src/main/AndroidManifest.xml
   create android/app/src/main/res/values/strings.xml
   create android/app/src/main/res/values/styles.xml
identical android/build.gradle
identical android/gradle.properties
   create android/keystores/BUCK
   create android/keystores/debug.keystore.properties
identical android/settings.gradle
   create android/app/src/main/res/mipmap-hdpi/ic_launcher.png
   create android/app/src/main/res/mipmap-mdpi/ic_launcher.png
   create android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
   create android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
   create android/gradle/wrapper/gradle-wrapper.jar
   create android/gradle/wrapper/gradle-wrapper.properties
   create android/gradlew
   create android/gradlew.bat
identical android/app/src/main/java/com/universalrelayboilerplate/MainActivity.java
^[[A^[[D^[[A
> fsevents@1.0.12 install /Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
2016-06-28 03:33:44.798 xcodebuild[3454:104444] Build settings from command line:
2016-06-28 03:33:44.799 xcodebuild[3454:104444]     TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault
2016-06-28 03:33:44.799 xcodebuild[3454:104444]     XCODE_DEFAULT_TOOLCHAIN_OVERRIDE = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  SOLINK_MODULE(target) Release/.node
ld: warning: URGENT: building for OSX, but linking against dylib (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/libstdc++.dylib) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking against dylib (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/lib/libSystem.dylib) built for iOS. Note: This will be an error in the future.
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:11:10: fatal error: 'CoreServices/CoreServices.h' file not found
#include "CoreServices/CoreServices.h"
         ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64"
gyp ERR! cwd /Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node --module_name=fse --module_path=/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 15.5.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents
node-pre-gyp ERR! node -v v6.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node --module_name=fse --module_path=/Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64' (1)
npm WARN install:fsevents@1.0.12 fsevents@1.0.12 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fsevents@1.0.12 Exit status 1
npm WARN isomorphic-relay@0.7.0 requires a peer of react-relay@0.8.0 || 0.9.0 but none was installed.
npm WARN relay-local-schema@0.5.0 requires a peer of graphql@^0.5.0 but none was installed.
To run your app on Android:
   Have an Android emulator running (quickest way to get started), or a device connected
   cd /Users/developer/Documents/_temp/testandr/UniversalRelayBoilerplate
   react-native run-android
```

Next thing to try: http://stackoverflow.com/questions/37419640/react-native-npm-install-fatal-error-coreservices-coreservices-h-file-not-fou

**Comment by thelordoftheboards** [comment]
Upgrading to [React Native 0.29-rc](https://github.com/facebook/react-native/releases/tag/v0.29.0-rc.0) is apparently not the cure.

**Comment by thelordoftheboards** [comment]
After the upgrade to RN 0.29-rc and re-creating the RN part of the project I was able to run from Android studio. Please try.

**Comment by thelordoftheboards** [comment]
@linonetwo have you been able to run the project through Android Studio?

**Comment by linonetwo** [comment]
Thank you, I was busy building a naive app for a cook near our university, sorry for my late reply.

I reclone the repo, npm run dev still give lots of error like:

`                                                                                                               
[1]                                                                                                            
[1] > UniversalRelayBoilerplate@7.5.0 dev-server C:\Users\onetwo\Desktop\UniversalRelayBoilerplate             
[1] > better-npm-run dev-server                                                                                
[1]                                                                                                            
[0]                                                                                                            
[0] > UniversalRelayBoilerplate@7.5.0 dev-webpack C:\Users\onetwo\Desktop\UniversalRelayBoilerplate            
[0] > rm -rf build && better-npm-run dev-webpack                                                               
[0]                                                                                                            
[2]                                                                                                            
[2] > UniversalRelayBoilerplate@7.5.0 start C:\Users\onetwo\Desktop\UniversalRelayBoilerplate                  
[2] > node node_modules/react-native/local-cli/cli.js start --reset-cache                                      
[2]                                                                                                            
[1] running better-npm-run in C:\Users\onetwo\Desktop\UniversalRelayBoilerplate                                
[1] Executing script: dev-server                                                                               
[1]                                                                                                            
[1] to be executed: "nodemon --exec ./node_modules/.bin/babel-node -- ./server/server.js"                      
[0] running better-npm-run in C:\Users\onetwo\Desktop\UniversalRelayBoilerplate                                
[0] Executing script: dev-webpack                                                                              
[0]                                                                                                            
[0] to be executed: "./node_modules/.bin/webpack-dev-server --hot --inline --no-info --colors"                 
[0] '.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���                                                                          
[0] ���������ļ���                                                                                              
[0]                                                                                                            
[0] npm                                                                                                        
[0]  ERR! Windows_NT 10.0.10586                                                                                
[0] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm
-cli.js" "run" "dev-webpack"                                                                                   
[0] npm ERR! node v6.2.0                                                                                       
[0] npm ERR! npm  v3.8.9                                                                                       
[0] npm                                                                                                        
[0] ERR! code ELIFECYCLE                                                                                       
[0] npm ERR! UniversalRelayBoilerplate@7.5.0 dev-webpack: `rm -rf build && better-npm-run dev-webpack`         
[0] npm ERR! Exit status 1                                                                                     
[0] npm ERR!                                                                                                   
[0] npm ERR! Failed at the UniversalRelayBoilerplate@7.5.0 dev-webpack script 'rm -rf build && better-npm-run d
ev-webpack'.                                                                                                   
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.                               
[0] npm ERR! If you do, this is most likely a problem with the UniversalRelayBoilerplate package,              
[0] npm ERR! not with npm itself.                                                                              
[0] npm ERR! Tell the author that this fails on your system:                                                   
[0] npm ERR!     rm -rf build && better-npm-run dev-webpack                                                    
[0] npm ERR! You can get information on how to open an issue for this project with:                            
[0] npm ERR!     npm bugs UniversalRelayBoilerplate                                                            
[0] npm ERR! Or if that isn't available, you can get their info via:                                           
[0] npm ERR!     npm owner ls UniversalRelayBoilerplate                                                        
[0] npm ERR! There is likely additional logging output above.                                                  
[0]                                                                                                            
[0] npm ERR! Please include the following file with any support request:                                       
[0] npm ERR!     C:\Users\onetwo\Desktop\UniversalRelayBoilerplate\npm-debug.log                               
[0] npm run dev-webpack exited with code 1                                                                     
[1] [nodemon] 1.9.2                                                                                            
[1] [nodemon] to restart at any time, enter `rs`                                                               
[1] [nodemon] watching: *.*                                                                                    
[1] [nodemon] starting `./node_modules/.bin/babel-node ./server/server.js`                                     
[1] '.' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���                                                                          
[1] ���������ļ���                                                                                              
[1] [nodemon] app crashed - waiting for file changes before starting...                                        
--> Sending SIGTERM to other processes..                                                                       
[2]  ┌────────────────────────────────────────────────────────────────────────────┐                            
[2]  │  Running packager on port 8081.                                            │                            
[2]  │                                                                            │                            
[2]  │  Keep this packager running while developing on any JS projects. Feel      │                            
[2]  │  free to close this tab and run your own packager instance if you          │                            
[2]  │  prefer.                                                                   │                            
[2]  │                                                                            │                            
[2]  │  https://github.com/facebook/react-native                                  │                            
[2]  │                                                                            │                            
[2]  └────────────────────────────────────────────────────────────────────────────┘                            
[2] Looking for JS files in                                                                                    
[2]    C:\Users\onetwo\Desktop\UniversalRelayBoilerplate                                                       
[2]                                                                                                            
[2] [20:18:36] <START> Building Dependency Graph                                                               
[2] [20:18:36] <START> Crawling File System                                                                    
[2] [Hot Module Replacement] Server listening on /hot                                                          
[2]                                                                                                            
[2] React packager ready.                                                                                      
[2]                                                                                                            
[2] [20:18:57] <END>   Crawling File System (21429ms)                                                          
[2] [20:18:57] <START> Building in-memory fs for JavaScript                                                    
[2] [20:18:58] <END>   Building in-memory fs for JavaScript (188ms)                                            
[2] [20:18:58] <START> Building in-memory fs for Assets                                                        `

**Comment by linonetwo** [comment]
react-native run-android is ok now. So there is no need to run with Android Studio now~

But all server things are buggy under windows, same in my own project, likes 

`var visitor = require("babel-helper-builder-react-jsx")({ /*istanbul ignore next*/
                                                         ^

TypeError: require(...) is not a function
    at exports.default (index.js:14:17)`

I use babel run time to avoid it, which is not a long term work. I'm considering returning to linux some day ...

**Comment by thelordoftheboards** [comment]
Right now I can test only on MacOS. If you submit a PR to better windows support, I would gladly accept it and attempt to preserve its functionality in future development. Is it OK for now to close this issue since you have a workaround?

**Comment by linonetwo** [comment]
I will have a try :)

**Comment by linonetwo** [comment]
I found that:

`"dev-prod": "export NODE_ENV=production && ./node_modules/.bin/babel-node ./server/server.js",`

can't exercise correctly in windows since babel-node don't recognize '.' in windows, showing up '.' is not an exercisable program or so.

I myself tried the tech that use a bin directory, and in ./bin/server.js, require('../server.babel'); // babel registration (runtime transpilation for node) and then : 

server.babel.js :
`var fs = require('fs');

var babelrc = fs.readFileSync('./.babelrc');
var config;

try {
  config = JSON.parse(babelrc);
} catch (err) {
  console.error('==>     ERROR: Error parsing your .babelrc.');
  console.error(err);
}

require('babel-register')(config);`

so I can write:

package.json
`
...
    "start-dev": {
      "command": "node ./bin/server.js",
      "env": {
        "NODE_ENV": "development"
      }
    }
...
`

to bootstrap dev mode instead of directly using babel-node.

Seems '.' problem will only show up in package.json ... I'm still researching, can you accept the workaround of using a ./bin folder?

**Comment by linonetwo** [comment]
Another possibility:

Community think ./node_modules/.bin/webpack-dev-server should be change to webpack-dev-server.

Can you tell me why we use all the programs under ./node_modules/.bin/ ? I don't understand.

**Comment by linonetwo** [comment]
Since I myself use:

`  
...
"betterScripts": {
  "watch-client": {
      "command": "node webpack/webpack-dev-server.js",
...
`
to bootstrap, instead of : 
`
"betterScripts": {
  "dev-webpack": {
      "command": "./node_modules/.bin/webpack-dev-server --hot --inline --no-info --colors"
...
`

**Comment by thelordoftheboards** [comment]
@linonetwo the changes you are describing should still work on Mac and should not be too complicated. If you can, please make a PR, I'd gladly merge it as long as it works without detriment on Mac. I currently do not have a way to test on Windows so I will rely on your help with that.

**Comment by shemsargent-rvtd** [comment]
I'm just getting started with URB, but I've been a Windows Admin for years. I'm not sure if this is helpful here and now, but the issue with the ".bin" folder might be resolvable with a little trick: Windows normally interprets .bin as a blank filename with the extension "bin". You can force it find the filename ".bin" with no extension by putting another period at the end like ".bin." Pretty goofy, I know. Here's a reference: http://www.hanselman.com/blog/HowToCreateAFileWithADotPrefixInWindowsExplorer.aspx

**Comment by shemsargent-rvtd** [comment]
I added some Windows-specific scripts to package.json. The additional script names end in "-windows". They replace Bash commands with Windows commands and successfully accesses the ".bin" folder by referring to  it as ".bin." Using the new scripts, I was able to launch the site on Windows 10.

**Comment by thelordoftheboards** [comment]
@shemsargent-rvtd if I understand correctly, you would have duplicate versions of the scripts, something along the lines of:

```javascript
  "scripts": {
    ...
    "build-schema": "./node_modules/.bin/babel-node ./scripts/build-schema.js",
    "build-schema-windows": "./node_modules/.bin./babel-node ./scripts/build-schema.js",
    ...
}
```

If this is correct, we can have the best of both worlds. I would appreciate if you can PR. @M1chaelTran, would that solution work for your purposes too?

And also I would suggest something shorter than `-windows`, maybe `-w`. After all, it has to be typed all the time.

**Comment by shemsargent-rvtd** [comment]
Yes, that is correct. I changed the script names to end with "-w" as you suggested and made a pull request. I didn't make Windows versions of all the scripts yet, just the ones I needed to get the server started.

**Comment by thelordoftheboards** [comment]
@shemsargent-rvtd please feel free to PR any other changes that are required for Windows (and Android on Windows) development. As long as they are not detrimental to using the repository on OS X, there is absolutely no reason not to have them.

**Comment by thelordoftheboards** [comment]
All Windows related tools and scripts will be created in the [urb-tools-windows](https://github.com/codefoundries/UniversalRelayBoilerplate/tree/master/units/urb-tools-windows) unit as the need arises. The `build-units` script will take care of adding them when the windows support is required.
