### ISSUE TITLE
[server] Issue when deploying - ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#198]
When running on heroku:

```
~ $ node server/server.js
/app/node_modules/relay-local-schema/lib/NetworkLayer.js:49
    var _ref2 = _asyncToGenerator(regeneratorRuntime.mark(function _callee(requestType, request) {
                                  ^

ReferenceError: regeneratorRuntime is not defined
    at /app/node_modules/relay-local-schema/lib/NetworkLayer.js:49:35
    at /app/node_modules/relay-local-schema/lib/NetworkLayer.js:93:4
    at Object.<anonymous> (/app/node_modules/relay-local-schema/lib/NetworkLayer.js:100:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Comment by thelordoftheboards** [comment]
Some probably babel polyfill will have to be added or something of the sort.

**Comment by thelordoftheboards** [comment]
The problem is with `relay-local-schema` hence:

https://github.com/codefoundries/UniversalRelayBoilerplate/issues/217
