### ISSUE TITLE
[global] Broken build with migration of npm to yarn

### ISSUE THREAD

**Issue by AndrewZurn** [codefoundries/UniversalRelayBoilerplate#266]
It looks like the most recent commit (https://github.com/codefoundries/UniversalRelayBoilerplate/commit/ca818468513e5ac33a5b22053b4445a331c2c2aa) has broken a build with a fresh repo.

From a fresh pull:
```
yarn install v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 93.41s.
shannon:spac-fusion-editor -> yarn dev
yarn dev v0.16.1
$ rm -rf build && concurrently --kill-others "npm run dev-webpack" "npm run dev-server" "npm run start"
[1]
[1] > @13.4.2 dev-server /Users/shannon/dev/andrew/spac/spac-fusion-editor
[1] > better-npm-run dev-server
[1]
[0]
[0] > @13.4.2 dev-webpack /Users/shannon/dev/andrew/spac/spac-fusion-editor
[0] > rm -rf build && better-npm-run dev-webpack
[0]
[2]
[2] > @13.4.2 start /Users/shannon/dev/andrew/spac/spac-fusion-editor
[2] > node node_modules/react-native/local-cli/cli.js start --reset-cache
[2]
[0] running better-npm-run in /Users/shannon/dev/andrew/spac/spac-fusion-editor
[1] running better-npm-run in /Users/shannon/dev/andrew/spac/spac-fusion-editor
[0] Executing script: dev-webpack
[0]
[0] to be executed: ./node_modules/.bin/webpack-dev-server --hot --inline --no-info --colors
[1] Executing script: dev-server
[1]
[1] to be executed: ./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node -- ./server/server.js
[1] [nodemon] 1.11.0
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[1] [nodemon] starting `./node_modules/.bin/babel-node ./server/server.js`
[0] Running Webpack, process.env.NODE_ENV=undefined, version=13.4.2.105
[0]  http://localhost:8080/
[0] webpack result is served from http://undefined:8080/13.4.2.105/
[0] content is served from /Users/shannon/dev/andrew/spac/spac-fusion-editor
[1] { Error: ENOENT: no such file or directory, open '.env'
[1]     at Error (native)
[1]     at Object.fs.openSync (fs.js:640:18)
[1]     at Object.fs.readFileSync (fs.js:508:33)
[1]     at Object.config (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/dotenv/lib/main.js:30:37)
[1]     at Object.<anonymous> (/Users/shannon/dev/andrew/spac/spac-fusion-editor/server/log.js:9:21)
[1]     at Module._compile (module.js:556:32)
[1]     at loader (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
[1] { Error: ENOENT: no such file or directory, open '.env'
[1]     at Error (native)
[1]     at Object.fs.openSync (fs.js:640:18)
[1]     at Object.fs.readFileSync (fs.js:508:33)
[1]     at Object.config (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/dotenv/lib/main.js:30:37)
[1]     at Object.<anonymous> (/Users/shannon/dev/andrew/spac/spac-fusion-editor/server/defaultRequestLoggerAuth.js:8:21)
[1]     at Module._compile (module.js:556:32)
[1]     at loader (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
[1] undefined:1
[1] undefined
[1] ^
[1]
[1] SyntaxError: Unexpected token u in JSON at position 0
[1]     at Object.parse (native)
[1]     at Object.<anonymous> (/Users/shannon/dev/andrew/spac/spac-fusion-editor/server/defaultRequestLoggerAuth.js:11:25)
[1]     at Module._compile (module.js:556:32)
[1]     at loader (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:154:7)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12)
[1]     at Function.Module._load (module.js:424:3)
[1]     at Module.require (module.js:483:17)
[1]     at require (internal/module.js:20:19)
[1] [nodemon] app crashed - waiting for file changes before starting...
[2] Scanning 1021 folders for symlinks in /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules (16ms)
[2]  ┌────────────────────────────────────────────────────────────────────────────┐
[2]  │  Running packager on port 8081.                                            │
[2]  │                                                                            │
[2]  │  Keep this packager running while developing on any JS projects. Feel      │
[2]  │  free to close this tab and run your own packager instance if you          │
[2]  │  prefer.                                                                   │
[2]  │                                                                            │
[2]  │  https://github.com/facebook/react-native                                  │
[2]  │                                                                            │
[2]  └────────────────────────────────────────────────────────────────────────────┘
[2] Looking for JS files in
[2]    /Users/shannon/dev/andrew/spac/spac-fusion-editor
[2]
[2] [Hot Module Replacement] Server listening on /hot
[2]
[2] React packager ready.
[2]
[2] jest-haste-map: @providesModule naming collision:
[2]   Duplicate module name: lodash
[2]   Paths: /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/babel-core/node_modules/lodash/package.json collides with /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/async/node_modules/lodash/package.json
[2]
[2] This warning is caused by a @providesModule declaration with the same name across two different files.
[2] jest-haste-map: @providesModule naming collision:
[2]   Duplicate module name: lodash
[2]   Paths: /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/babel-register/node_modules/lodash/package.json collides with /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/async/node_modules/lodash/package.json
[2]
[2] This warning is caused by a @providesModule declaration with the same name across two different files.
[2] [10/31/2016, 10:22:09 PM] <START> Initializing Packager
[2] [10/31/2016, 10:22:09 PM] <START> Building in-memory fs for JavaScript
[2] [10/31/2016, 10:22:10 PM] <END>   Building in-memory fs for JavaScript (695ms)
[2] [10/31/2016, 10:22:10 PM] <START> Building Haste Map
[2] [10/31/2016, 10:22:11 PM] <END>   Building Haste Map (755ms)
[2] [10/31/2016, 10:22:11 PM] <END>   Initializing Packager (1785ms)
^C[1] npm run dev-server exited with code null
```

Looks like maybe a `yarn setup-local` might do the trick from package.json.

```
shannon:spac-fusion-editor -> yarn setup-local
yarn setup-local v0.16.1
$ cp ./configuration/default.env ./.env && cp ./configuration/app/default.publicURL.js ./configuration/app/publicURL.js && npm run update-default-persister -- memory && npm run update-ip && react-native link

> @13.4.2 update-default-persister /Users/shannon/dev/andrew/spac/spac-fusion-editor
> babel-node ./scripts/update-default-persister.js "memory"

Written: /Users/shannon/dev/andrew/spac/spac-fusion-editor/configuration/graphql/defaultPersister.js

> @13.4.2 update-ip /Users/shannon/dev/andrew/spac/spac-fusion-editor
> babel-node ./scripts/update-ip.js

IP Address:192.168.3.114
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './ios/Rebar/AppDelegate.m'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at updateIPInFile (/Users/shannon/dev/andrew/spac/spac-fusion-editor/scripts/update-ip.js:41:22)
    at Object.<anonymous> (/Users/shannon/dev/andrew/spac/spac-fusion-editor/scripts/update-ip.js:15:3)
    at Module._compile (module.js:556:32)
    at loader (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "update-ip"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! @13.4.2 update-ip: `babel-node ./scripts/update-ip.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @13.4.2 update-ip script 'babel-node ./scripts/update-ip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./scripts/update-ip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shannon/dev/andrew/spac/spac-fusion-editor/npm-debug.log
error Command failed with exit code 1.
```

That runs into an error as well, looks like something to with Rebar.

I was able to get the app up and running after that though, even though it didn't complete successfully.

```
shannon:spac-fusion-editor -> yarn dev
yarn dev v0.16.1
$ rm -rf build && concurrently --kill-others "npm run dev-webpack" "npm run dev-server" "npm run start"
[0]
[0] > @13.4.2 dev-webpack /Users/shannon/dev/andrew/spac/spac-fusion-editor
[0] > rm -rf build && better-npm-run dev-webpack
[0]
[1]
[1] > @13.4.2 dev-server /Users/shannon/dev/andrew/spac/spac-fusion-editor
[1] > better-npm-run dev-server
[1]
[2]
[2] > @13.4.2 start /Users/shannon/dev/andrew/spac/spac-fusion-editor
[2] > node node_modules/react-native/local-cli/cli.js start --reset-cache
[2]
[1] running better-npm-run in /Users/shannon/dev/andrew/spac/spac-fusion-editor
[0] running better-npm-run in /Users/shannon/dev/andrew/spac/spac-fusion-editor
[1] Executing script: dev-server
[1]
[1] to be executed: ./node_modules/.bin/nodemon --exec ./node_modules/.bin/babel-node -- ./server/server.js
[0] Executing script: dev-webpack
[0]
[0] to be executed: ./node_modules/.bin/webpack-dev-server --hot --inline --no-info --colors
[1] [nodemon] 1.11.0
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[1] [nodemon] starting `./node_modules/.bin/babel-node ./server/server.js`
[2] Scanning 1021 folders for symlinks in /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules (31ms)
[2]  ┌────────────────────────────────────────────────────────────────────────────┐
[2]  │  Running packager on port 8081.                                            │
[2]  │                                                                            │
[2]  │  Keep this packager running while developing on any JS projects. Feel      │
[2]  │  free to close this tab and run your own packager instance if you          │
[2]  │  prefer.                                                                   │
[2]  │                                                                            │
[2]  │  https://github.com/facebook/react-native                                  │
[2]  │                                                                            │
[2]  └────────────────────────────────────────────────────────────────────────────┘
[2] Looking for JS files in
[2]    /Users/shannon/dev/andrew/spac/spac-fusion-editor
[2]
[2] [Hot Module Replacement] Server listening on /hot
[2]
[2] React packager ready.
[2]
[0] Running Webpack, process.env.NODE_ENV=undefined, version=13.4.2.105
[0]  http://127.0.0.1:8080/
[0] webpack result is served from http://127.0.0.1:8080/13.4.2.105/
[0] content is served from /Users/shannon/dev/andrew/spac/spac-fusion-editor
[2] jest-haste-map: @providesModule naming collision:
[2]   Duplicate module name: lodash
[2]   Paths: /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/babel-register/node_modules/lodash/package.json collides with /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/async/node_modules/lodash/package.json
[2]
[2] This warning is caused by a @providesModule declaration with the same name across two different files.
[2] jest-haste-map: @providesModule naming collision:
[2]   Duplicate module name: lodash
[2]   Paths: /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/babel-core/node_modules/lodash/package.json collides with /Users/shannon/dev/andrew/spac/spac-fusion-editor/node_modules/react-native/node_modules/async/node_modules/lodash/package.json
[2]
[2] This warning is caused by a @providesModule declaration with the same name across two different files.
[2] [10/31/2016, 10:26:36 PM] <START> Initializing Packager
[2] [10/31/2016, 10:26:36 PM] <START> Building in-memory fs for JavaScript
[2] [10/31/2016, 10:26:37 PM] <END>   Building in-memory fs for JavaScript (725ms)
[2] [10/31/2016, 10:26:37 PM] <START> Building Haste Map
[2] [10/31/2016, 10:26:39 PM] <END>   Building Haste Map (1307ms)
[2] [10/31/2016, 10:26:39 PM] <END>   Initializing Packager (2415ms)
[1] info: Starting application name=urb, version=13.4.2.105, NODE_ENV=development, HOST=127.0.0.1, PORT=4444, PUBLIC_URL=http://localhost:4444, process_title=/usr/local/Cellar/node/6.6.0/bin/node, process_pid=2988, local_ip=192.168.3.114
[1] DEVELOPMENT. Server listening on 127.0.0.1
```

So it looks like documentation or the build script might need to be updated, and also that issue with Rebar.

**Comment by thelordoftheboards** [comment]
Sorry about the mix up. I will fix it up shortly. The documentation is indeed missing the step for setup-local. As for Rebar, this is just a mistake, it should say UniversalRelayBoilerplate.

**Comment by thelordoftheboards** [comment]
I believe I fixed the issues, can you please try again?

**Comment by AndrewZurn** [comment]
Just retested, it seems like the order of setup should be:

- git clone
- yarn
- yarn setup-local 

Running `yarn setup-local` before yarn complained about missing dependencies (or at least it looks like that might be the issue).

```
shannon:spac-fusion-editor -> yarn setup-local
yarn setup-local v0.16.1
$ cp ./configuration/default.env ./.env && cp ./configuration/app/default.publicURL.js ./configuration/app/publicURL.js && npm run update-default-persister -- memory && npm run update-ip && react-native link

> @13.4.2 update-default-persister /Users/shannon/dev/andrew/spac/spac-fusion-editor
> babel-node ./scripts/update-default-persister.js "memory"

sh: babel-node: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "update-default-persister" "--" "memory"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @13.4.2 update-default-persister: `babel-node ./scripts/update-default-persister.js "memory"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @13.4.2 update-default-persister script 'babel-node ./scripts/update-default-persister.js "memory"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node ./scripts/update-default-persister.js "memory"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shannon/dev/andrew/spac/spac-fusion-editor/npm-debug.log
error Command failed with exit code 1.
```

After re-running in the order above everything completed successfully and the servers came up correctly from the looks of it.

Looks like just updating that last tidbit in the README to the correct order should resolve the remainder of the issues.

Thanks for the quick turn-around, much appreciated!

Andrew

**Comment by thelordoftheboards** [comment]
Sorry about this, .md dyslexia. Thank you for catching it. Hope it goes smoother for you from here on.
