### ISSUE TITLE
[webapp] Upgrade webpack.HotModuleReplacementPlugin to a version compatible with Webpack 3.0

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#306]
in `webpack.config.babel`. The current version causes the error:

```
xxxx/urb/main/node_modules/webpack/lib/HotModuleReplacementPlugin.js:59
                                records.chunkModuleIds[chunk.id] = chunk.mapModules(function(m) {
                                                                         ^
TypeError: chunk.mapModules is not a function
        at xxxx/urb/main/node_modules/webpack/lib/HotModuleReplacementPlugin.js:59:46
```

**Comment by mu-yu** [comment]
same problem with error:
```
xxxxxxxxxx\node_modules\webpack\lib\HotModuleReplacementPlugin.js:59
                                        records.chunkModuleIds[chunk.id] = chunk.mapModules(m => m.id);
                                                                                 ^

TypeError: chunk.mapModules is not a function
    at chunks.forEach.chunk (xxxxxxxxxx\node_modules\webpack\lib\HotModuleReplacementPlugin.js:59:47)
```

**Comment by thelordoftheboards** [comment]
@mu-yu have you been able to resolve the issue?

**Comment by mu-yu** [comment]
the issue was fixed by fix webpack config. maybe it's config issues rather than code issue.
see the right config in my project called "everain.me"

**Comment by dzc944262316** [comment]
I have also encountered this problem

**Comment by thelordoftheboards** [comment]
Works in new version.
