### ISSUE TITLE
Initialise .env before attempting to access it

### ISSUE THREAD

**Issue by tombull** [codefoundries/UniversalRelayBoilerplate#32]
When following the instructions at [Initial Project Setup On Local Machine](http://codefoundries.com/developer/rebar/development-setup.html), it instructs the user to run `npm install` before running `npm run setup-local`.
Unfortunately, running `npm install` immediately after cloning the project results in the following error:

```
> babel-node ./scripts/build-schema.js

babel-relay-plugin-loader: using schema at [/Users/tom/projects/urbp/graphql/schema.json]
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/Users/tom/projects/urbp/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (CassandraOptions.js:6:21)
    at Module._compile (module.js:541:32)
    at loader (/Users/tom/projects/urbp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tom/projects/urbp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/Users/tom/projects/urbp/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (log.js:7:21)
    at Module._compile (module.js:541:32)
    at loader (/Users/tom/projects/urbp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tom/projects/urbp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
{ Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.module.exports.config (/Users/tom/projects/urbp/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (ObjectManagerBase.js:13:21)
    at Module._compile (module.js:541:32)
    at loader (/Users/tom/projects/urbp/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/tom/projects/urbp/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

This is because the file `.env` has not been initialised later in the instruction `npm run setup-local`.

**Comment by thelordoftheboards** [comment]
These errors can be ignored. I will update the documentation.
I know there is no elegance to it, but the process is tailored towards facilitating the Heroku deployment and I could not find any better way. If you come up with something more elegant please feel free to PR.
