### ISSUE TITLE
Naming collision in react native

### ISSUE THREAD

**Issue by tombull** [codefoundries/UniversalRelayBoilerplate#33]
When following the instructions at [Initial Project Setup On Local Machine](http://codefoundries.com/developer/rebar/development-setup.html), at the stage of running a `npm run start` from a fresh clone of the project, the following error is encountered:

```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/tom/projects/urbp/node_modules/react/lib/TouchHistoryMath.js collides with /Users/tom/projects/urbp/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: TouchHistoryMath
  Paths: /Users/tom/projects/urbp/node_modules/react/lib/TouchHistoryMath.js collides with /Users/tom/projects/urbp/node_modules/react-native/Libraries/vendor/react/browser/eventPlugins/TouchHistoryMath.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/Users/tom/projects/urbp/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:160:15)
    at /Users/tom/projects/urbp/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:125:25

```

**Comment by thelordoftheboards** [comment]
Unfortunately this is the case. I assume something to do with React 15 and the RC of React Native 0.25. I will re-try this once the official release of 0.25 is ready, hopefully it will resolve the problem.

**Comment by tombull** [comment]
In the meantime, maybe update the documentation to remind developers that they can use the web portions of the system without the react native portions by using `npm run dev`.

**Comment by thelordoftheboards** [comment]
Good idea! Will do.
