### ISSUE TITLE
[server] Flow preset for babel does not allow webpack to run

### ISSUE THREAD

**Issue by thelordoftheboards** [codefoundries/UniversalRelayBoilerplate#452]
On branch `develop`:

```
$ yarn dev
yarn run v1.5.1
$ ./node_modules/.bin/concurrently --kill-others "npm run dev-relay" "npm run dev-webpack" "npm run dev-server"
[1]
[1] > UniversalRelayBoilerplate@0.7.0 dev-webpack /cfw/urb/main
[1] > webpack-dev-server --mode development --hot --inline --no-info --colors
[1]
[0]
[0] > UniversalRelayBoilerplate@0.7.0 dev-relay /cfw/urb/main
[0] > relay-compiler --src ./units/ --extensions=js jsx --schema schema.graphql --watch
[0]
[2]
[2] > UniversalRelayBoilerplate@0.7.0 dev-server /cfw/urb/main
[2] > export NODE_ENV=development && ./node_modules/.bin/babel-watch -e js,jsx ./units/urb-base-server/server.js
[2]
[0]
[0] Writing js
[0] Unchanged: 43 files
[0] Watching for changes to js...
[0] Watching for changes to graphql...
[1] /cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:162
[1]     throw new Error(`Plugin/Preset files are not allowed to export objects, only functions. In ${filepath}`);
[1]     ^
[1]
[1] Error: Plugin/Preset files are not allowed to export objects, only functions. In /cfw/urb/main/node_modules/babel-preset-flow/lib/index.js
[1]     at createDescriptor (/cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:162:11)
[1]     at items.map (/cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:87:50)
[1]     at Array.map (<anonymous>)
[1]     at createDescriptors (/cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
[1]     at createPresetDescriptors (/cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
[1]     at presets (/cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:61:19)
[1]     at presets (/cfw/urb/main/node_modules/@babel/core/lib/config/config-descriptors.js:51:25)
[1]     at mergeChainOpts (/cfw/urb/main/node_modules/@babel/core/lib/config/config-chain.js:308:26)
[1]     at /cfw/urb/main/node_modules/@babel/core/lib/config/config-chain.js:271:7
[1]     at buildRootChain (/cfw/urb/main/node_modules/@babel/core/lib/config/config-chain.js:119:22)
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! UniversalRelayBoilerplate@0.7.0 dev-webpack: `webpack-dev-server --mode development --hot --inline --no-info --colors`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the UniversalRelayBoilerplate@0.7.0 dev-webpack script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /Users/alex/.npm/_logs/2018-05-19T22_13_01_195Z-debug.log
[1] npm run dev-webpack exited with code 1
--> Sending SIGTERM to other processes..
[0] npm run dev-relay exited with code null
[2] npm run dev-server exited with code null
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c ./node_modules/.bin/concurrently --kill-others \"npm run dev-relay\" \"npm run dev-webpack\" \"npm run dev-server\"
Directory: /cfw/urb/main
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/cfw/urb/main/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by thelordoftheboards** [comment]
Resolved by upgrading deps, and possibly removing unused units.
